language: node_js
node_js:
- 0.1
env:
  matrix:
    secure: f3QffPS0kEmEolObGhsY4nf3AufGS5OhQpultUx0d0rcgCT4tcgqgX59TnCKVpKWA/kzJCvNquN7oOndNbMOai+Qm+IdTYd/oVRvfREjqn0hoW+vXnpJPAjc4Jc5loWdKlmhkqC3JqmRtYpJ20o4wVdsoFNLl9zKAQ/IAUQrL6iz6aPz5E7r44ToP4TdFcp4D1eOQ+HumwHvyJGptn20mFBY2rfkZYgQhEeB5kwWijJrjhHb/Xz8buEIAbZK1XQ+FNXPWhIEBtIlOFmbEr/oTUMP/hSs9yKPDpDBYFfIlkP4EcqXjrjT6VHv/3pvMzsK1RMq9HxWULH+kJB23uxeEVbVKNSQxXob7gPAkhz4ENszWjKk2jg6rCQ1nEQy0e0hemhsqUQAgL5CBx+E8Yt0ZuVbMElARrQgErmRXmJdJv8t7/n8fdi0+DJZOmE80xngrjYX6ukjkaNc+eH9s5fPOq8XG6lmj1EipqGAyOlJ4fICh3P5v7FjjvmsegamrfnKe2sYGNP1yX6bZhEiEuqYr1U/PIZP891w+bw6Fw8a8bxgNBRzJzvdweRENh/8udWY23lr0UnWB6fT3AqnBce4meoqVvKphcBKBLTNXy36hC7e11PErZOFsM3xUHROOPLc3KOeLaosm/JhK+DcXdJzS5SeVs4JYwx1pNgcYhbD/tA=
